version: "3.8"
services:
  db:
    image: postgres:15
    container_name: organize-simple-db-frontend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: untrained0
      POSTGRES_DB: organize-simple-frontend
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432' 
volumes:
  db_data:
   name: organize-simple-data-frontend
